### ISSUE TITLE
Error running 

### ISSUE THREAD

**Issue by kevzy** [yasirarism/MissKatyPyro#60]
Im having this error while running the program    

sudo docker run misskaty
Password:
Traceback (most recent call last):
  File "<frozen runpy>", line 189, in _run_module_as_main
  File "<frozen runpy>", line 148, in _get_module_details
  File "<frozen runpy>", line 112, in _get_module_details
  File "/MissKaty/misskaty/__init__.py", line 58, in <module>
    user.start()
  File "/usr/local/lib/python3.11/dist-packages/pyrogram/sync.py", line 66, in async_to_sync_wrap
    return loop.run_until_complete(coroutine)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/pyrogram/methods/utilities/start.py", line 58, in start
    is_authorized = await self.connect()
                    ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/pyrogram/methods/auth/connect.py", line 40, in connect
    await self.load_session()
  File "/usr/local/lib/python3.11/dist-packages/pyrogram/client.py", line 587, in load_session
    await self.storage.open()
  File "/usr/local/lib/python3.11/dist-packages/pyrogram/storage/memory_storage.py", line 61, in open
    base64.urlsafe_b64decode(self.session_string + "=" * (-len(self.session_string) % 4))
  File "/usr/lib/python3.11/base64.py", line 134, in urlsafe_b64decode
    return b64decode(s)
           ^^^^^^^^^^^^
  File "/usr/lib/python3.11/base64.py", line 88, in b64decode
    return binascii.a2b_base64(s, strict_mode=validate)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
binascii.Error: Incorrect padding

**Comment by yasirarism** [comment]
You fill wrong userbot session string maybe, if you did not need userbot don't fill session vars

**Comment by kevzy** [comment]
how do I get user session

**Comment by yasirarism** [comment]
> how do I get user session

It's for userbot, you can generate from @misskatyrobot using /genstring command. But this is optional. Don't fill it if you didn't need userbot function
